### ISSUE TITLE
플러그인 명세서 작성

### ISSUE THREAD

**Issue by wpkorea** [wpkorea/ivy-utils#4]
ivy-utils 플러그인의 명세서가 있어야 할 것 같아요. 꼭 필요한 플러그인이고, 예전부터 만들고 싶었던 플러그인입니다. 혼자 기획하고 혼자 만들어 나가는 것보다 다른 사람의 의견을 수렴하고 토론하면서 개발해 나가면 좋을 것 같습니다. 

플러그인의 용도가 무엇인지, 어떤 주요 기능들이 포함될 예정인지, 사용하는 방법은 어떤 것이 있는지 등등 정보를 공유바랍니다. 그래야 다른 사람들이 추가하고 싶은 기능이 있거나, 버그가 있거나, 테스트를 하거나 등등 의견과 Contribution이 가능할 것 같습니다. 

READM 파일에 좀더 구체적으로 기본적인 개발 의도와 초기 스펙, 그리고 향후 어떤 형태로 발전을 시켜나갈 것인지 기록이 되면 도움이 될 것 같습니다.

**Comment by changwoo-ivy** [comment]
README.md 에 간단한 문서 작성되었습니다. 그리고 플러그인의 라이센스는 GPLv2입니다. 앞으로 wordpress.org 제출을 목표로 할 겁니다.

앞으로 플러그인 제작에 대한 사항은 제가 리드하고 싶습니다. 비록 이 플러그인이 아이비넷이라는 회사의 이름을 달고 있고, 또 회사에서 중요한 자원이 된다 하더라도 제가 핵심 개발을 진행하고 있고 앞으로도 그럴 것이란 사실은 명백합니다. 서포트를 받는 것은 감사합니다. 오픈인만큼 그 누구의 도움도 감사하지요. 그러나 제가 리딩하고 있다는 사실은 명확하며 이것만큼은 존중받고 싶습니다.

이슈를 종료합니다.
